require:
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

inherit_from:
  - https://wonolo.github.io/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.7

RSpec/FilePath:
  Include:
    - '_spec.rb$'
