require:
  - rubocop-rspec

inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml
  - https://wonolo.github.io/ruby-style-guide/rubocop.yml

AllCops:
  RSpec:
    Patterns:
    - '_spec.rb$'
