require:
  - rubocop-rspec

inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml
  - https://wonolo.github.io/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.6

RSpec/FilePath:
  Include:
    - '_spec.rb$'
